[package]
name = "git-history-polisher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17" , features = ["derive"]}
chrono = "0.4.22"
rand = "0.8.5" 
lipsum = "0.8.2"
